### ISSUE TITLE
TextureMap is private to the library

### ISSUE THREAD

**Issue by TotoShampoin** [chip2n/zig-obj#8]
Hey! So, now that the lib supports texture options, I can make use of .path and .opts to load textures.

The only problem is that TextureMap is not marked as `pub` in the library, meaning it cannot be used as a function's parameter.  
That is to say, I can't have a simple `parseTexture(map: TextureMap)`, not without doing an arguably unnecessary conversion first.

Is there a reason not to expose TextureMap? Or is it a simple oversight?

**Comment by chip2n** [comment]
Just a simple oversight - should be resolved now :+1:
